server.port: ${forex_service_port}

spring:
  application.name: forex-service
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource.url: jdbc:h2:mem:testdb
  data.jpa.repositories.bootstrap-mode: default
  h2.console.enabled: true

management:
    endpoint.health.enabled: true
    endpoints:
        web:
            base-path: /actuator/info
            exposure:
                include: health
        enabled-by-default: false


