server.port: ${currency_conversion_service_port}

spring:
  application.name: currency-conversion-service
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8080/realms/${keycloak_realm_name}
            user-name-attribute: preferred_username
            authorization-uri: http://localhost:8080/realms/${keycloak_realm_name}/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/${keycloak_realm_name}/protocol/openid-connect/token
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            client-id: ${keycloak_realm_client_id}
            client-secret: ${keycloak_realm_client_secret}
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
            scope: openid

management:
    endpoint.health.enabled: true
    endpoints:
        web:
            base-path: /actuator/info
            exposure:
                include: health
        enabled-by-default: false
