spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

management:
    endpoint.health.enabled: true
    endpoints:
        web:
            base-path: /actuator/info
            exposure:
                include: health
        enabled-by-default: false


server:
  port: 9191


logging:
    level:
        org.springframework.security: DEBUG